spring:
  application:
    name: service-addition

server:
  port: 8010

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env
        #https://docs.spring.io/spring-boot/docs/2.1.7.RELEASE/reference/html/production-ready-endpoints.html
  endpoint:
    env:
      show-values: WHEN_AUTHORIZED
      #ALWAYS
  info:
    env:
      enabled: true

info:
  app:
    name: EurekaClient Clase12 service-addition
  java:
    version: ${java.version}
